# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build container app to Azure Container Registry - sdai-sbox-gh-actions-app001

on:
  workflow_run:
    workflows: ["Python application"]
    branches: ["main"]
    types: 
      - completed
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://sdailabsboxeuwacr01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_daa1c22753664ee6913bc2c12707f733 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_01fdc665b73940ef9367eb2b698d5fab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sdailabsboxeuwacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_daa1c22753664ee6913bc2c12707f733 }}/ghactions:${{ github.sha }}
        file: ./Dockerfile
