# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy app to Azure - sdai-sbox-gh-actions-app001

on:
  workflow_run:
    workflows: ["02-build_push_sdai-sbox-gh-actions-app001"]
    branches: ["main"]
    types: 
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sdailabsboxeuwacr01.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_daa1c22753664ee6913bc2c12707f733 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_01fdc665b73940ef9367eb2b698d5fab }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "sdai-sbox-gh-actions-app001"
        slot-name: "production"
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_192e6045d819434c914f6e189154ade3 }}
        images: 'sdailabsboxeuwacr01.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_daa1c22753664ee6913bc2c12707f733 }}/ghactions:${{ github.sha }}'
