name: Set date as env. variable
# This var is only available in this workflow
on: 
# Manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MY_VAR: ${{ vars.MY_VAR }}
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # UTC time
      - name: Echo Env var. set in repo
        run: echo $MY_VAR
